<?php

/**
 * Implements hook_menu().
 */
function islandora_scholar_profile_menu() {

}

/**
 * Implements hook_prepare().
 */
function islandora_scholar_profile_prepare($node) {
  
}

/**
 * Implements hook_init().
 */
function islandora_scholar_profile_init() {
  $path = drupal_get_path('module', 'islandora_scholar_profile');
  drupal_add_css($path . '/css/islandora-person.css');
}

/**
 * Implements hook_theme_registry_alter().
 */
function islandora_scholar_profile_theme_registry_alter(&$theme_registry) {
  $path = drupal_get_path('module', 'islandora_scholar_profile');
  $theme_registry['islandora_person']['template'] = $path . '/templates/islandora-person';
  $theme_registry['islandora_person']['theme path'] = $path;
}

/**
 * Implements hook_xml_form_builder_get_form_modify_definition_alter().
 * Updates forms to include u1 and u2 fields.
 *
 * @param $form
 * @param $form_state
 */
function islandora_scholar_profile_xml_form_builder_get_form_modify_definition_alter(&$form, &$form_state) {
 if (isset($form_state['association']) && $form_state['association']['dsid'] == 'MODS') {
   // Make sure citations and thesis have extra mapping fields
   if(in_array($form_state['association']['content_model'], array('ir:citationCModel', 'ir:thesisCModel'))) {
     $form['u12_fieldset'] = array(
       '#type' => 'fieldset',
       '#access' => true,
       '#collapsed' => FALSE,
       '#title' => 'Profile Identifiers',
       '#description' => t('U1 and U2 identifiers to link this object with a(many) department(s) and a(many) researcher(s)'),
       'u1_identifier_tabs' => array (
         '#type' => 'tabs',
         '#access' => true,
         '#autocomplete_path' => 'islandora_autocomplete/islandora:personCModel/mads.identifier',
         '#required' => false,
         '#title' => 'Faculty Identifier(s)',
         '#tree' => true,
         'u1_identifier_tabpanel' =>
           array (
             '#type' => 'tabpanel',
             '#access' => true,
             '#autocomplete_path' => 'islandora_autocomplete/islandora:personCModel/mads.identifier',
             '#description' => 'This is the faculty member\'s username. If more than one faculty member is required, select Add button and add another identifier.',
             '#required' => false,
             '#tree' => true,
             '#actions' =>
               array (
                 'create' => NULL,
                 'read' =>
                   array (
                     'path' => '/mods:mods/mods:identifier[@type=\'u1\']',
                     'context' => 'document',
                   ),
                 'update' => NULL,
                 'delete' =>
                   array (
                     'path' => 'self::node()',
                     'context' => 'self',
                   ),
               ),
             'u1_identifier_text' =>
               array (
                 '#type' => 'textfield',
                 '#access' => true,
                 '#autocomplete_path' => 'islandora_autocomplete/islandora:personCModel/mads.username',
                 '#required' => false,
                 '#tree' => true,
                 '#actions' =>
                   array (
                     'create' =>
                       array (
                         'path' => '/mods:mods',
                         'context' => 'document',
                         'schema' => '',
                         'type' => 'xml',
                         'prefix' => NULL,
                         'value' => '<identifier type="u1">%value%</identifier>',
                       ),
                     'read' =>
                       array (
                         'path' => 'self::node()',
                         'context' => 'parent',
                       ),
                     'update' => NULL,
                     'delete' => NULL,
                   ),
               ),
           ),
       ),
       'u2_identifier_tabs' => array (
       '#type' => 'tabs',
       '#access' => true,
       '#autocomplete_path' => 'islandora_autocomplete/islandora:organizationCModel/mads.identifier',
       '#description' => t('This is the departmental identifier. If more than one department is required, select Add button and add another identifier. Ensure that you are using an <b>authorized departmental</b> name from the IslandScholar list.'),
       '#required' => false,
       '#title' => 'Departmental Identifier(s)',
       '#tree' => true,
       'u2_identifier_tabpanel' =>
         array (
           '#type' => 'tabpanel',
           '#access' => true,
           '#autocomplete_path' => 'islandora_autocomplete/islandora:organizationCModel/mads.identifier',
           '#description' => t('This is the departmental identifier. If more than one department is required, select Add button and add another identifier.'),
           '#required' => false,
           '#tree' => true,
           '#actions' =>
             array (
               'create' => NULL,
               'read' =>
                 array (
                   'path' => '/mods:mods/mods:identifier[@type=\'u2\']',
                   'context' => 'document',
                 ),
               'update' => NULL,
               'delete' =>
                 array (
                   'path' => 'self::node()',
                   'context' => 'self',
                 ),
             ),
           'u2_identifier_text' =>
             array (
               '#type' => 'textfield',
               '#access' => true,
               '#autocomplete_path' => 'islandora_autocomplete/islandora:organizationCModel/mads.namePart/',
               '#required' => false,
               '#tree' => true,
               '#actions' =>
                 array (
                   'create' =>
                     array (
                       'path' => '/mods:mods',
                       'context' => 'document',
                       'schema' => '',
                       'type' => 'xml',
                       'prefix' => NULL,
                       'value' => '<identifier type="u2">%value%</identifier>',
                     ),
                   'read' =>
                     array (
                       'path' => 'self::node()',
                       'context' => 'parent',
                     ),
                   'update' => NULL,
                   'delete' => NULL,
                 ),
             ),
         ),
     )
     );
   }
 }
}
